# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcb718946a7a076e37780b9f2e28d997e2a3fb368460bff661261f51fad9ec73eb62c83b50f13b5e89a0a1956e7ab75c34e64b6c976617f336ec127449e11bd4

test:
  secret_key_base: 5daa95252957e1bde5f79e503ef1e034c438fe2387219bb48cdcddebecf44b313196ef41d61cdff164ffef86513e2beca664918705d375292cd6021e4978df8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
